version: '3'
name: CPIT-405

services:
  # PHP application service
  php:
    build:
      context: ./php
    container_name: CPIT-405-php-app
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  # PostgreSQL database service
  postgres:
    image: postgres:15
    container_name: CPIT-405-postgres-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
  # pgAdmin service for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: CPIT-405-pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    name: CPIT-405-network
    driver: bridge

volumes:
  postgres_data:
    name: CPIT-405-postgres-data